with customerai_vw as (
SELECT ORDER_ID, CUSTOMER_ID, ORDER_DATE, STATUS AS ORDER_STATUS, FIRST_NAME, LAST_NAME AS GIVEN_NAME
FROM DQLABS_QA.CUSTOMERAI.CUSTOMERAI_DBT_INCR
)
select * from customerai_vw